#!/bin/bash
## This script takes the metagenome from SALSA as an input
## It aligns reads, generates binning data, and visualizes
## The RNA-seq assembly by 

#!/bin/bash
#SBATCH --job-name=ANVIOspadesL3A
#SBATCH --partition=bigmemm
#SBATCH --mincpus=30
#SBATCH --mem-per-cpu=8000
module load hmmer prodigal python3 bowtie2 hisat2/2.0.3-beta samtools stringtie/1.3.2d

anvi-script-reformat-fasta \
-l 1000 \
--simplify-names \
-o ./contigs-fixed.fa \
/path/to/metagenome.fasta

anvi-gen-contigs-database \
-f ./contigs-fixed.fa \
-o ./metagenome.db

anvi-run-hmms \
-c ./metagenome.db \
-T 30

##ALIGNMENT AND SORTING
bowtie2-build  \
-f ./contigs-fixed.fa \
./bowtiemetagenomedb

##############\/\/\/\/\/ under construction \/\/\/\/\/
bowtie2-align \
-x ./bowtiemetagenomedb \
-p 30 \
-1 /path/to/metagenome1.fastq -q \
-2 /home/weirdlob/RAWsequenceDATA/seq1/L3A_CGATGTAT_L002_R2_001.fastq -q \
-S ./library1.sam

samtools view -bS ./library1.sam > ./library1.bam

bowtie2-align --fast -x ./bowtiemetagenomedb -p 30 -1 /home/weirdlob/RAWsequenceDATA/seq2/ChIP1_ACAGTG_L001_R1_001.fastq -q -2 /home/weirdlob/RAWsequenceDATA/seq2/ChIP1_ACAGTG_L001_R2_001.fastq -q -S ./library2.sam
samtools view -bS ./library2.sam > ./library2.bam

bowtie2-align --fast -x ./bowtiemetagenomedb -p 30 -1 /home/weirdlob/RAWsequenceDATA/seq2/ChIP2_GTGAAA_L001_R1_001.fastq -q -2 /home/weirdlob/RAWsequenceDATA/seq2/ChIP2_GTGAAA_L001_R2_001.fastq -q -S ./library3.sam
samtools view -bS ./library3.sam > ./library3.bam

hisat2-build ./contigs-fixed.fa ./hisatmetagenomedb
hisat2-align -p 30 -x ./hisatmetagenomedb --novel-splicesite-outfile ./novelsplicesitees -1 /home/weirdlob/RAWsequenceDATA/seq4/L3A_GCCAATAT_L001_R1_001.fastq -2 /home/weirdlob/RAWsequenceDATA/seq4/L3A_GCCAATAT_L001_R2_001.fastq -S ./RNAseq.sam
samtools view -bS ./RNAseq.sam > ./RNAseq.bam
